- type: job
  id: OverseerSRM
  name: job-name-overseer
  description: job-description-overseer
  playTimeTracker: JobOverseerSRM
  ranks:
    RatRankSRMOverseerSenior:
    - !type:CharacterPlaytimeRequirement
      tracker: JobOverseerSRM
      min: 72000 # 20 hours
    RatRankSRMOverseerMiddle:
    - !type:CharacterPlaytimeRequirement
      tracker: JobOverseerSRM
      min: 36000 # 10 hours
    RatRankSRMOverseerJunior: []
  weight: 100
  startingGear: OverseerGear
  alwaysUseSpawner: true
  whitelisted: true # Rat
  requireAdminNotify: false
  icon: "JobIconOverseer"
  supervisors: job-supervisors-srm-overseer
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "SRM"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:SexRequirement
      sex: Male
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
  access:
  - Command
  - Hunter
  - HunterSenior
  - HunterOverseer
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: SRM
      - type: LanguageAdder
        addSpoken:
          - Saintspact
          - HighImperial
          - LowImperial
          - Tradeband
        addUnderstood:
          - Saintspact
          - HighImperial
          - LowImperial
          - Tradeband
      - type: InnatePsionicPowers
        powersToAdd:
          - TelepathyPower
          - AssayPower

- type: startingGear
  id: OverseerGear
  equipment:
    id: OverseerPDA
    ears: ClothingHeadsetHunter
    jumpsuit: ClothingUniformJumpsuitOverseer
    head: ClothingHeadHatHunterOverseer
    shoes: ClothingShoesBootsHunter
    outerClothing: ClothingOuterArmorHunterDusterOverseer
    gloves: ClothingHandsGlovesHunter
    pocket2: RomaineBible
    belt: ClothingBeltAssault
    back: ClothingBackpackSRM
  storage:
    back:
      - PietyRedeemableHigh
      - PietyRedeemableHigh
      - PietyRedeemableHigh
