- type: job
  id: MarshalCMM
  name: job-name-marshal
  description: job-description-marshal
  playTimeTracker: JobMarshalCMM
  ranks:
    RatRankCMMMarshalHigh:
    - !type:CharacterPlaytimeRequirement
      tracker: JobMarshalCMM
      min: 72000 # 20 hours
    RatRankCMMMarshalLead:
    - !type:CharacterPlaytimeRequirement
      tracker: JobMarshalCMM
      min: 36000 # 10 hours
    RatRankCMMMarshalSenior: []
  weight: 39
  startingGear: MarshalGear
  alwaysUseSpawner: true
  whitelisted: true # Rat
  requireAdminNotify: false
  icon: "JobIconMarshal"
  supervisors: job-supervisors-cmm-marshal
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 126000
    - !type:FactionRequirement
        factionID: "TSP"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: TSP
      - type: LanguageAdder
        addSpoken:
          - American
          - Tradeband
        addUnderstood:
          - American
          - Tradeband
  accessGroups:
  - GeneralAccess
  access:
  - Command
  - Maintenance
  - Minuteman
  - MinutemanPrison
  - MinutemanRankingOfficer
  - MinutemanMarshal
  - CMMFunds
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - GliessSheriff
  - GliessDockmaster

- type: startingGear
  id: MarshalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMMOfficer
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatCMMMarshal
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMinutemanPouches
    back: ClothingBackpackMinuteman
    pocket1: WeaponCaptainRevolverShotgun
    pocket2: RatRubberStampCMMMarshal
    id: MarshalPDA
    ears: ClothingHeadsetCMM
    outerClothing: ClothingOuterArmorCMMCarapace
