- type: rank
  id: RatRankCommandantSenior
  name: Генерал-полковник
  prefix: Генерал-полк.
  paygrade: О6

- type: rank
  id: RatRankCommandantMiddle
  name: Генерал-лейтенант
  prefix: Генерал-лейт.
  paygrade: О5

- type: rank
  id: RatRankCommandantJunior
  name: Генерал-майор
  prefix: Генерал-майор
  paygrade: О4

