using Content.Shared.Administration;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Administration.UI.Tabs.PlayerTab;

[GenerateTypedNameReferences]
public sealed partial class PlayerTabEntry : PanelContainer
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public PlayerTabEntry(
        PlayerInfo player,
        StyleBoxFlat styleBoxFlat)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        var roles = _entMan.System<SharedRoleSystem>();

        var rolePrototype = player.RoleProto == null ? null : _prototype.Index(player.RoleProto.Value);

        UsernameLabel.Text = player.Username;
        if (!player.Connected)
            UsernameLabel.StyleClasses.Add("Disabled");
        JobLabel.Text = player.StartingJob;

    }
}
