- type: rank
  id: RatRankCourtierFirst
  name: Герцог
  prefix: Герцог
  paygrade: П6

- type: rank
  id: RatRankCourtierHead
  name: Маркиз
  prefix: Маркиз
  paygrade: П5

- type: rank
  id: RatRankCourtierLead
  name: Граф
  prefix: Граф
  paygrade: П4

- type: rank
  id: RatRankCourtierSenior
  name: Виконт
  prefix: Виконт
  paygrade: П3

- type: rank
  id: RatRankCourtierMiddle
  name: Барон
  prefix: Барон
  paygrade: П2

- type: rank
  id: RatRankCourtierJunior
  name: Патриций
  prefix: Патриций
  paygrade: П1