- type: rank
  id: RatRankGovernorSenior
  name: Эрцгерцог
  prefix: Эрцгерцог
  paygrade: Д6

- type: rank
  id: RatRankGovernorMiddle
  name: Герцог
  prefix: Герцог
  paygrade: Д5

- type: rank
  id: RatRankGovernorJunior
  name: Маркграф
  prefix: Маркграф
  paygrade: Д4