using Content.Client.Cargo.Components;
using Content.Client.Cargo.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System.Numerics;

namespace Content.Client.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class PriceMonitorWindow : DefaultWindow
{
    private readonly PriceMonitorSystem _priceSystem;

    public PriceMonitorWindow(PriceMonitorSystem priceSystem)
    {
        RobustXamlLoader.Load(this);
        
        _priceSystem = priceSystem;
        
        RefreshButton.OnPressed += _ => OnRefresh();
        
        CreateGoodsHeader();
        CreateShuttlesHeader();
    }

    private void CreateGoodsHeader()
    {
        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal
        };
        
        header.AddChild(new Label { Text = Loc.GetString("price-monitor-good-id"), MinSize = new Vector2(150, 20) });
        header.AddChild(new Label { Text = Loc.GetString("price-monitor-base-price"), MinSize = new Vector2(100, 20) });
        header.AddChild(new Label { Text = Loc.GetString("price-monitor-current-price"), MinSize = new Vector2(100, 20) });
        header.AddChild(new Label { Text = Loc.GetString("price-monitor-multiplier"), MinSize = new Vector2(80, 20) });
        header.AddChild(new Label { Text = Loc.GetString("price-monitor-change"), MinSize = new Vector2(80, 20) });
        
        GoodsList.AddChild(header);
    }

    private void CreateShuttlesHeader()
    {
        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal
        };
        
        header.AddChild(new Label { Text = Loc.GetString("price-monitor-shuttle-name"), MinSize = new Vector2(200, 20) });
        header.AddChild(new Label { Text = Loc.GetString("price-monitor-base-price"), MinSize = new Vector2(100, 20) });
        header.AddChild(new Label { Text = Loc.GetString("price-monitor-current-price"), MinSize = new Vector2(100, 20) });
        header.AddChild(new Label { Text = Loc.GetString("price-monitor-change"), MinSize = new Vector2(80, 20) });
        
        ShuttlesList.AddChild(header);
    }

    public void UpdatePrices(PriceMonitorData monitor)
    {
        while (GoodsList.ChildCount > 1)
        {
            GoodsList.RemoveChild(GoodsList.GetChild(1));
        }
        
        while (ShuttlesList.ChildCount > 1)
        {
            ShuttlesList.RemoveChild(ShuttlesList.GetChild(1));
        }
        
        foreach (var (goodId, data) in monitor.GoodsPrices)
        {
            var row = CreateGoodsRow(data);
            GoodsList.AddChild(row);
        }
        
        foreach (var (_, data) in monitor.ShuttlePrices)
        {
            var row = CreateShuttleRow(data);
            ShuttlesList.AddChild(row);
        }
    }

    private BoxContainer CreateGoodsRow(PriceData data)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal
        };
        
        row.AddChild(new Label { Text = data.GoodId, MinSize = new Vector2(150, 20) });
        row.AddChild(new Label { Text = $"{data.BasePrice:N0}", MinSize = new Vector2(100, 20) });
        row.AddChild(new Label { Text = $"{data.CurrentPrice:N0}", MinSize = new Vector2(100, 20) });
        row.AddChild(new Label { Text = $"{data.Multiplier:F2}x", MinSize = new Vector2(80, 20) });
        
        var changeColor = data.Trend >= 0 ? Color.LimeGreen : Color.Red;
        var changeLabel = new Label
        {
            Text = $"{data.Trend:+0.0;-0.0}%",
            FontColorOverride = changeColor,
            MinSize = new Vector2(80, 20)
        };
        row.AddChild(changeLabel);
        
        return row;
    }

    private BoxContainer CreateShuttleRow(ShuttlePriceData data)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal
        };
        
        row.AddChild(new Label { Text = data.ShuttleName, MinSize = new Vector2(200, 20) });
        row.AddChild(new Label { Text = $"{data.BasePrice:N0}", MinSize = new Vector2(100, 20) });
        row.AddChild(new Label { Text = $"{data.CurrentPrice:N0}", MinSize = new Vector2(100, 20) });
        
        var changeColor = data.PercentChange >= 0 ? Color.LimeGreen : Color.Red;
        var changeLabel = new Label
        {
            Text = $"{data.PercentChange:+0.0;-0.0}%",
            FontColorOverride = changeColor,
            MinSize = new Vector2(80, 20)
        };
        row.AddChild(changeLabel);
        
        return row;
    }

    private void OnRefresh()
    {
        _priceSystem.RequestPrices();
    }
}
