<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(TargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Content.ModuleManager</RootNamespace>
  </PropertyGroup>
  <Import Project="..\RobustToolbox\Imports\Shared.props" />
</Project>
