- type: job
  id: WorkerNCWL
  name: job-name-ncwl-newbie
  description: job-description-ncwl-newbie
  playTimeTracker: JobWorkerNCWL
  ranks:
    RatRankNCWLEnlistedTop:
    - !type:CharacterPlaytimeRequirement
      tracker: JobWorkerNCWL
      min: 252000 # 70 hours
    RatRankNCWLEnlistedBased:
    - !type:CharacterPlaytimeRequirement
      tracker: JobWorkerNCWL
      min: 216000 # 60 hours
    RatRankNCWLEnlistedHigh:
    - !type:CharacterPlaytimeRequirement
      tracker: JobWorkerNCWL
      min: 180000 # 50 hours
    RatRankNCWLEnlistedLead:
    - !type:CharacterPlaytimeRequirement
      tracker: JobWorkerNCWL
      min: 144000 # 40 hours
    RatRankNCWLEnlistedSenior:
    - !type:CharacterPlaytimeRequirement
      tracker: JobWorkerNCWL
      min: 108000 # 30 hours
    RatRankNCWLEnlistedMiddle:
    - !type:CharacterPlaytimeRequirement
      tracker: JobWorkerNCWL
      min: 72000 # 20 hours
    RatRankNCWLEnlistedJunior:
    - !type:CharacterPlaytimeRequirement
      tracker: JobWorkerNCWL
      min: 36000 # 10 hours
    RatRankNCWLEnlistedNovice: []
  weight: 1
  startingGear: WorkerNCWLGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconNCWLWorker"
  supervisors: job-supervisors-ncwl-worker
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: NCWL
      - type: LanguageAdder
        addSpoken:
          - Dockta
        addUnderstood:
          - Dockta
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: WorkerNCWLGear
  equipment:
    shoes: ClothingShoesBootsSalvage
    jumpsuit: ClothingUniformJumpsuitNCWLTrainee
    id: NCWLWorkerPDA
    belt: ClothingBeltSalvageWebbingCrescentFilled
    back: ClothingBackpackNCWL
    ears: ClothingHeadsetNCWL
