- type: job
  id: ArtificerNCWL
  name: job-name-ncwl-industry-artificer
  description: job-description-ncwl-industry-artificer
  playTimeTracker: JobEngineeringWorkerNCWL
  ranks:
    RatRankNCWLEnlistedTop:
    - !type:CharacterPlaytimeRequirement
      tracker: JobEngineeringWorkerNCWL
      min: 216000 # 60 hours
    RatRankNCWLEnlistedBased:
    - !type:CharacterPlaytimeRequirement
      tracker: JobEngineeringWorkerNCWL
      min: 180000 # 50 hours
    RatRankNCWLEnlistedHigh:
    - !type:CharacterPlaytimeRequirement
      tracker: JobEngineeringWorkerNCWL
      min: 144000 # 40 hours
    RatRankNCWLEnlistedLead:
    - !type:CharacterPlaytimeRequirement
      tracker: JobEngineeringWorkerNCWL
      min: 108000 # 30 hours
    RatRankNCWLEnlistedSenior:
    - !type:CharacterPlaytimeRequirement
      tracker: JobEngineeringWorkerNCWL
      min: 72000 # 20 hours
    RatRankNCWLEnlistedMiddle:
    - !type:CharacterPlaytimeRequirement
      tracker: JobEngineeringWorkerNCWL
      min: 36000 # 10 hours
    RatRankNCWLEnlistedJunior: []
  weight: 93
  startingGear: ArtificerNCWLGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconNCWLEngineeringWorker"
  supervisors: job-supervisors-ncwl-unionized
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 1000
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: NCWL
      - type: LanguageAdder
        addSpoken:
          - Dockta
        addUnderstood:
          - Dockta
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - NCWLGeneral
  - NCWLJail
  - NCWLArmory
  - NCWLCommand

- type: startingGear
  id: ArtificerNCWLGear
  equipment:
    shoes: ClothingShoesBootsSalvage
    jumpsuit: ClothingUniformJumpsuitNCWLArtificer
    id: NCWLEngineeringWorkerPDA
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesColorYellow
    head: ClothingHeadHatBeretEngineering
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetNCWL
    belt: ClothingBeltSalvageWebbingCrescentFilled

