- type: job
  id: DoctorNCWL
  name: job-name-ncwl-medical-doctor
  description: job-description-ncwl-medical-doctor
  playTimeTracker: JobMedicalWorkerNCWL
  ranks:
    RatRankNCWLEnlistedTop:
    - !type:CharacterPlaytimeRequirement
      tracker: JobMedicalWorkerNCWL
      min: 216000 # 60 hours
    RatRankNCWLEnlistedBased:
    - !type:CharacterPlaytimeRequirement
      tracker: JobMedicalWorkerNCWL
      min: 180000 # 50 hours
    RatRankNCWLEnlistedHigh:
    - !type:CharacterPlaytimeRequirement
      tracker: JobMedicalWorkerNCWL
      min: 144000 # 40 hours
    RatRankNCWLEnlistedLead:
    - !type:CharacterPlaytimeRequirement
      tracker: JobMedicalWorkerNCWL
      min: 108000 # 30 hours
    RatRankNCWLEnlistedSenior:
    - !type:CharacterPlaytimeRequirement
      tracker: JobMedicalWorkerNCWL
      min: 72000 # 20 hours
    RatRankNCWLEnlistedMiddle:
    - !type:CharacterPlaytimeRequirement
      tracker: JobMedicalWorkerNCWL
      min: 36000 # 10 hours
    RatRankNCWLEnlistedJunior: []
  weight: 95
  startingGear: DoctorNCWLGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconNCWLMedicalWorker"
  chatNameColor: "#00e6d6"
  supervisors: job-supervisors-ncwl-unionized
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 1000
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: NCWL
      - type: CPRTraining
      - type: SurgerySpeedModifier
        speedModifier: 1.75
      - type: HealingSpeedModifier # Ratgore-tweak
        speedModifier: 2.0 # Ratgore-tweak
      - type: LanguageAdder
        addSpoken:
          - Dockta
        addUnderstood:
          - Dockta
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: DoctorNCWLGear
  equipment:
    shoes: ClothingShoesBootsCombat
    jumpsuit: ClothingUniformJumpsuitNCWLMedic
    id: NCWLMedicalWorkerPDA
    outerClothing: ClothingOuterArmorNCWLMedi
    belt: ClothingBeltMedicalFilled
    back: ClothingBackpackNCWL
    pocket1: HandheldCrewMonitorNCWL # Ratgore-tweak
    gloves: ClothingHandsGlovesNitrile
    head: ClothingHeadHatNCWLCapsoftMedical
    eyes: ClothingEyesHudMedical
    ears: ClothingHeadsetNCWL
