using Content.Client.Message;
using Content.Shared._Crescent.Misc;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Crescent.Misc;

[GenerateTypedNameReferences]
public sealed partial class AutominerWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    private TimeSpan _cooldownEnd = TimeSpan.Zero;
    private bool _isActive;

    public Action? OnStartButtonPressed;

    public AutominerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        StartButton.OnPressed += _ => OnStartButtonPressed?.Invoke();
    }

    public void UpdateState(AutominerBoundUserInterfaceState state)
    {
        _cooldownEnd = state.CooldownEndTime;
        _isActive = state.IsActive;
        UpdateDisplay();
    }

    private void UpdateDisplay()
    {
        if (_isActive && _timing.CurTime < _cooldownEnd)
        {
            var timeLeft = _cooldownEnd - _timing.CurTime;
            TimerLabel.SetMarkup(Loc.GetString("autominer-timer", ("time", $"{timeLeft.Minutes:0}:{timeLeft.Seconds:00}")));
            StatusLabel.SetMarkup(Loc.GetString("autominer-status-active"));
            StartButton.Disabled = true;
        }
        else
        {
            TimerLabel.SetMarkup(Loc.GetString("autominer-timer-ready"));
            StatusLabel.SetMarkup(Loc.GetString("autominer-status-idle"));
            StartButton.Disabled = false;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateDisplay();
    }
}